from Misc import *

filenames = [
    'fps_task_juice_tracker_ict_filter_',
    'fps_task_juice_tracker_nn_filter_',
    'fps_task_mugI_tracker_esm_filter_',
    'fps_task_mugI_tracker_ict_filter_',
    'fps_task_mugI_tracker_nn_filter_',
    'fps_task_mugII_tracker_esm_filter_',
    'fps_task_mugII_tracker_ict_filter_',
    'fps_task_mugII_tracker_nn_filter_',
    'fps_task_mugIII_tracker_esm_filter_',
    'fps_task_mugIII_tracker_ict_filter_',
    'fps_task_mugIII_tracker_nn_filter_',
    'error_task_bookI_tracker_esm_filter_',
    'error_task_bookI_tracker_ict_filter_',
    'error_task_bookI_tracker_nn_filter_',
    'error_task_bookII_tracker_esm_filter_',
    'error_task_bookII_tracker_ict_filter_',
    'error_task_bookII_tracker_nn_filter_',
    'error_task_bookIII_tracker_esm_filter_',
    'error_task_bookIII_tracker_ict_filter_',
    'error_task_bookIII_tracker_nn_filter_',
    'error_task_cereal_tracker_esm_filter_',
    'error_task_cereal_tracker_ict_filter_',
    'error_task_cereal_tracker_nn_filter_',
    'error_task_juice_tracker_esm_filter_',
    'error_task_juice_tracker_ict_filter_',
    'error_task_juice_tracker_nn_filter_',
    'error_task_mugI_tracker_esm_filter_',
    'error_task_mugI_tracker_ict_filter_',
    'error_task_mugI_tracker_nn_filter_',
    'error_task_mugII_tracker_esm_filter_',
    'error_task_mugII_tracker_ict_filter_',
    'error_task_mugII_tracker_nn_filter_',
    'error_task_mugIII_tracker_esm_filter_',
    'error_task_mugIII_tracker_ict_filter_',
    'error_task_mugIII_tracker_nn_filter_',
    'fps_task_bookI_tracker_esm_filter_',
    'fps_task_bookI_tracker_ict_filter_',
    'fps_task_bookI_tracker_nn_filter_',
    'fps_task_bookII_tracker_esm_filter_',
    'fps_task_bookII_tracker_ict_filter_',
    'fps_task_bookII_tracker_nn_filter_',
    'fps_task_bookIII_tracker_esm_filter_',
    'fps_task_bookIII_tracker_ict_filter_',
    'fps_task_bookIII_tracker_nn_filter_',
    'fps_task_cereal_tracker_esm_filter_',
    'fps_task_cereal_tracker_ict_filter_',
    'fps_task_cereal_tracker_nn_filter_',
    'fps_task_juice_tracker_esm_filter_'
]
#for filename in filenames:
#    aggregateDataFromFiles(filename, filename)

getPointPlot(file='list')
